sudo: required

language: bash

services:
  - docker


install:
  - docker build -t osipovaleks/docker-jenkins-android .
  - docker run -it --rm --name jenkins osipovaleks/docker-jenkins-android


script:
  - ./travisTest.sh
